ARG PHP_VERSION
FROM $PHP_VERSION

RUN mkdir -p /var/www/html/
RUN mkdir -p /var/www/html/public_html/
RUN mkdir -p /var/www/html/project/
RUN apt-get update && apt-get install -y  \
    zlib1g-dev \
    build-essential \
    git \
    curl \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libmcrypt-dev \
    libgd-dev \
    jpegoptim optipng pngquant gifsicle \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    libicu-dev \
    zip \
    sudo \
    unzip \
    npm \
    nodejs \
    autoconf \
    pkg-config \
    libssl-dev
    

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath soap zip gd intl opcache

RUN pecl install redis
RUN docker-php-ext-enable redis

RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg

RUN echo "clear_env = no" >> /usr/local/etc/php-fpm.d/www.conf

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
WORKDIR /var/www/html/project

RUN chown -Rf www-data:www-data /var/www/html
RUN chown -Rf www-data:www-data /var/www/html/public_html
RUN chown -Rf www-data:www-data /var/www/html/project